NueHappy
Add 2 missing webhook types.
Rework `Cycler` to have priority ordering.
Rename `GC_cycler` to `GC_CYCLER`
If running on pypy add `gc.collect` at the end of a `GC_CYCLER` cycle.
Add `ChannelBase.name`.
Add `ChannelBase.has_name_like`.
Add `Guild.get_channel_like` `type_` optional argument.

Do not display the source `KeyError` at the following traceback part:
```
...
  File ".../hata/ext/extension_loader/extension_loader.py", line 1286, in _load
    await self._load_extension(extension)
  File ".../hata/ext/extension_loader/extension_loader.py", line 1581, in _load_extension
    raise ExtensionError(message) from None
hata.ext.extension_loader.extension_loader.ExtensionError: ExtensionError (...):
Exception occured meanwhile loading an extension: `...`.

Traceback (most recent call last):
  File ".../hata/ext/extension_loader/extension_loader.py", line 428, in _load
    lib = sys.modules[spec.name]
KeyError('...')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..../hata/ext/extension_loader/extension_loader.py", line 1576, in _load_extension
    lib = await KOKORO.run_in_executor(extension._load)
  File "..../hata/ext/extension_loader/extension_loader.py", line 445, in _load
    spec.loader.exec_module(lib)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
...
```

Fix a possible infinit recursion error at `FlagBase.__repr__`.
`CommandProcesser` did not await all the check handlers correctly.
`CommandProcesser` could act at specific checks that if there is `None`, they did not pass either.
Fix an another `AttributeError` at `_check_base.__repr__`.
`CommandProcesser` used bad checks for `command_error`.
Fix an error when `Guild.get_channel_like` wanted to search between the roles of the guild.
Audio player did not stop in looping mode, when it should have.
Add `url` option to `ConverterFlag`, but remove `guild`.
add `MESSAGE_JUMP_URL_RP` to `URLS`.
Fix a hanging `AudioPlayer` thread issue. (not the same as the hanging `VoiceClient` one)
Add converter for `Message`.
Add converter for `Invite`.
Add `URLS.INVITE_URL_PATTERN`.
Rename `IS_ID_RP` to `ID_RP`.
Add `others.INVITE_CODE_RP`.
Add `other.is_invite_code`.