orindance
Fix:
```
  File ".../hata/discord/parsers.py", line 5928, in remove
    for index in reversed(range(len(asynclist))):
TypeError("'type' has no length",)
```

Fix:
```
  File ".../hata/discord/parsers.py", line 3921, in unextend
    parent.__delvent__(func,name,**kwargs)
AttributeError("'CommandProcesser' object has no attribute '__delvent__'",)
```

Fix:
```py
  File ".../hata/ext/commands/command.py", line 1503, in __call__
    if user.has_role(self.roles):
  File ".../hata/discord/user.py", line 901, in has_role
    guild = role.guild
AttributeError("'set' object has no attribute 'guild'",)
```

`CommandProcesser.__delevent__` did not delete the given `func` from it's category if was not passed as `Command` instance.
Fix a bug at `ClientDictionary.append`.
Make `Invite` "immortal".
Add `Invite.partial`.
Add `Invite.precreate`.
Add `INVITES`.
Remove `Invite.__init__` -> Add `Invite.__new__`.
Remove `Invite._update` and `Invite._update_no_return`. -> Add `Invite._update_counts_only`, `Invite._update_attributes`, `Invite._set_attributes`.
`Invite.created_at` could be set as `None`.
Enable `instance_or_id_to_instance` to accept `tuple` of `type` for `type_` argument.
Enable `instance_or_id_to_snowflake` to accept `tuple` of `type` for `type_` argument.
Make `Invite` `DiscordEntity` subclass.
Add `DOCS_ENABLED` variable to see whether python is `-OO`.
Add `hata.ext.commands.utils.Closer`.
`WaitAndContinue.__call__` cancelled itself even if it received `False` from it's check.
`WaitAndContinue` could cancel itself with `None`. Modify it to `TimeoutError`.
Add `Guild.emoji_counts`.

Fix:
```py
  File ".../hata/ext/patchouli/module_mapper.py", line 410, in embed_sized
    docs = self.docs
  File ".../hata/ext/patchouli/module_mapper.py", line 366, in docs
    self._docs = docstring = self._get_raw_docstring()
  File ".../hata/ext/patchouli/module_mapper.py", line 444, in _get_raw_docstring
    parent = MAPPED_OBJECTS.get(self.path.parent)
  File ".../hata/ext/patchouli/qualpath.py", line 138, in __hash__
    hash_ = self.__hash
AttributeError('_QualPath__hash',)
```

Modify `QualPath.__hash` to `._hash`.
Do not support `__itruediv__` with `QualPath` anymore (changing hash value issues).
`QualPath.parent` never set `_hash` attribute.
`Guild.owner`'s data can not be included with guild payload, tho that case was not handled.
Add `Guild.thread_channels`.
Fixup `GravedListingElement.__repr__`.
`ListingHeadConverter` did not put `-` at the start of it's first line.
`listing_converter` could leave after the first yielded element.
Add missing `QualPath.__rtruediv__`.
Add `QualPath.__sub__`, `.__rsub__` and `._do_sub`.