hinaspin
Fix:
```py
  File ".../hata/backend/dereaddons_local.py", line 784, in __get__
    value = self.fget(obj)
  File ".../hata/ext/patchouli/module_mapper.py", line 410, in embed_sized
     docs = self.docs
  File ".../hata/ext/patchouli/module_mapper.py", line 366, in docs
    self._docs = docstring = self._get_raw_docstring()
  File ".../hata/ext/patchouli/module_mapper.py", line 448, in _get_raw_docstring
    docstring = parent.docstring
AttributeError("'TypeUnit' object has no attribute 'docstring'",)
```
`ChannelStore.permissions_for` could raise `AttributeError` if called from a partial channel.
`ChannelThread.permissions_for` could raise `AttributeError` if called from a partial channel.
`ChannelGuildUndefnied.permissions_for` could raise `AttributeError` if called from a partial channel.
`ChannelGuildBase.permissions_for` could raise `AttributeError` if called from a partial channel.
`ChannelText.permissions_for` could raise `AttributeError` if called from a partial channel.
`ChannelVoice.permissions_for` could raise `AttributeError` if called from a partial channel.
`Client.eula_get` could raise `AttributeError` (typo).
`AO2Access.created_at` was not set as `UTC` time.
Remove `Guild.roles` (ram usage), add `Guild.role_list` property instead.
Rename `Guild.all_role` to `.roles`.
Remove `Guild.channels` (ram usage), add `Guild.channel_list` property instead.
Rename `Guild.all_channel` to `.channels`.
Remove `Channelcategory.channels` (ram usage), add `ChannelCategory.channel_list` property instead.
Add `Guild.channel_list_flattened`.
`ChannelText.topic` defaults to `None` (from empty string) (faster empty check).
`GuildProfile.roles` defaults to `None` if empty (ram usage).
`Client.email` defaults to `None` (from empty string) (faster empty check).
`UserOA2.email defaults to `None` (from empty string) (faster empty check).
Fix some `NameError` at `HTTPClient._request2`.
`SubterraneanHelpCommand` could show up category help or command helps for those, when looking up by name, who had no permission to see them.
Rename `Request_CM` to `RequestCM`.
Fix up `RequestCM.__await__` and `.__iter__`.
Rename `Websocket_CM` to `WebsocketCM`.
Fix up `WebsocketCM.__await__` and `.__iter__`.
Add thread check for `Executor.create_future`.
Add full name check to `ChannelBase.get_user_like`.
Add full name check to `ChannelBase.get_users_like`.
Add full name check to `Guild.get_users_like`.
Add full name check to `ChannlGuildBase.get_user_like`.
Add full name check to `ChannelGuildBase.get_users_like`.
Fix a full name check, when after a full name check iteration, the name was modified, even if it should not have.
`Guild.default_role˛` returns `None` instead of raising, when the guild is partial.
Add string name option for `message.guild.default_role` / `message.channel.guild.default_role`.
Make `DATETIME_FORMAT_CODE` importable from hata.
Modify `ChannelTextBase._pop_multiple` to return the missed message id-s as well.
Add `HATA_ALLOW_DEAD_EVENTS` env variable.
Add `HATA_CUSTOM_CDN_ENDPOINT` env variable.
Add `HATA_CUSTOM_API_ENDPOINT` env variable.
Add `HATA_CUSTOM_DIS_ENDPOINT` env variable.
Add `MessageRepr` for represnting unchaced messages.
Update `MessageReference`, cached properties are not reasonably needed.
Update `MessageApplication` icon slots.
Resolve https://github.com/HuyaneMatsu/hata/issues/16
Add extra `ERROR_CODES.invalid_message_send_user` handling for `Pagination` and to familiar types.
Add `isawaitable`.
Support awaitable prefixes with `SubterraneanHelpCommand`.
Fix:
```py
  File ".../hata/ext/patchouli/module_mapper.py", line 412, in embed_sized
     docs = self.docs
  File ".../hata/ext/patchouli/module_mapper.py", line 368, in docs
    self._docs = docstring = self._get_raw_docstring()
  File ".../hata/ext/patchouli/module_mapper.py", line 568, in _get_raw_docstring
    return DocString(docstring, self.path)
  File ".../hata/ext/patchouli/parser.py", line 1349, in __new__
    sections = parse_docstring(docstring, path)
  File ".../hata/ext/patchouli/parser.py", line 1248, in parse_docstring
    sub_section = build_graves_on_subsection(sub_section, path)
  File ".../hata/ext/patchouli/graver.py", line 316, in build_graves_on_subsection
    element = build_graves_on_subsection(element, path)
  File ".../hata/ext/patchouli/graver.py", line 318, in build_graves_on_subsection
    element = element.graved(path)
  File ".../hata/ext/patchouli/parser.py", line 497, in graved
    return GravedTable(self, path)
  File ".../hata/ext/patchouli/graver.py", line 505, in __new__
    element, warnings = build_graves(element)
  File ".../hata/ext/patchouli/graver.py", line 245, in build_graves
    if grave_end >= len(text) or text[grave_end+1] != '`':
IndexError('string index out of range',
```
Extend warnings' message dropped by `build_graves`.
Fix two errors, when first and the last section could not be broke down.
Fix a `sizify` error, when put empty lines at the start.
`ChooseMenu.cancel` did not accept an optional `exception` parameter.
Fix a bug, when `Client.reaction_delete` somewhy added a reaction as well ????