koishiwink
`&` operation cannot be used on `set` and `list`, so use `.intersection` instead.
`ScarletLock` is now a subclass of `Lock`
Remove `hata.ext.commands.utils.prefix_by_guild` was not used anyways and I dont think so either it should be there.
`hata.ext.commands.utils.Timeouter.get_expiration_delay` could raise `AttributeError`.
`hata.ext.commands.utils.Timeouter` repeated it's timeout by default.
Add `IntegrationApplication`.
Add `Integration.application`.
Add `Webhook.application_id`.
`Integration.user` can be `ZEROUSER`.
Add `ActivityUnknown.CUSTOM_ID`
`preconvert_snowflake` did not accept string with length of 18-20 meanwhile it should have those as well.
Remove `Integration.account_name` and `Integration.account_id`, but add `Integration.account` and `IntegrationAccount` type. `Integration.account` can be `User` or `Client` type as well.
Add `ChannelGuildUndefnied`.
Add some endpoints, even tho, non of them is usable right now.
Add `ChannelThread`.
Use `Application.guild_id` over `.guild`.
`Application.rpc_origins` defaults to `None`.
`IconSlot` accepts `None` as `url_property` and `url_as_method` if they are not applied yet.
Add `Application.developers`.
Add `Application.hook`.
Add `Application.publishers`.
Add `Application.executables`.
Add `Application.third_party_skus`.
Add `Application.splash_hash`.
Add `Application.splash_type`.
Add `Application.splash`.
Add `Application.overlay`.
Add `Application.overlay_compatibility_hook`.
Add `Application.aliases`.
Add `Application.eula_id`.
Add `ApplicationSubEntity`.
Add `ApplicationExecutable`.
Add `ThirdPartySKU`.
Add `EULAS` weak value dict.
Add `EULA`.
Add `Client.eula_get`.
Remove `Application._fillup`.
Add `APPLICATIONS` weak value dict.
Make `Application` "immortal".
Remove `Application.__init__`.
Add `Application.__new__`.
Add `Application._create_empty`.
Add `Application._create_update`.
Remove `Application.__call__`.
Add `Application._update_no_return`.
Add `Client.applications_detecable`.
Rename `UserFlag.discord_employee` to `.staff`.
Rename `UserFlag.discord_partner` to `.partner`.
Add some new pretty printers-
Rename `UserFlag.hypesquad_events` to `.hypesquad`.
Rename `UserFlag.verified_bot_developer` to `.verified_developer`.
Add `UserFlag.team_pseudo_user`.
Fix hanging voice client issue when internet goes off.
Fix the following exception when destroying ghost voice clients:
```
Task exception was never retrieved
<Task FINISHED coro=VoiceClient._connect done defined at .../hata/discord/voice_client.py:653 exception=AttributeError("'NoneType' object has no attribute 'recv'",)>
Traceback (most recent call last):
  File ".../hata/discord/voice_client.py", line 723, in _connect
    await task
  File ".../hata/discord/gateway.py", line 822, in _poll_event
    message = await self.websocket.recv()
AttributeError("'NoneType' object has no attribute 'recv'",)
```
`ChannelText.precreate` did not set `.type` correctly.
`ChannelText._from_partial_data` now accepts `data` as `None` as well.
Add `ChannelText.DEFAULT_TYPE`.
`PartialEmoji` now also handles `emoji_{}` keys.
Add `WelcomeChannel`.
Add `WelcomeScreen`.
Add `Client.welcome_screen_get`.
`ChannelGuildBase` was never exported to `URLS` module, instead it was to `http`.
`ContentParser` returned the function instead of the parser.
`ContentParserMethod` never awaited `ContentParser.__call__`.
Add `ParserContextBase.__repr__`.
Add `RestParserContext.__repr__`.
Add `ConverterSetting.__repr__`.
Add `ParserContext.__repr__` (`SingleArgsParserContext` inherits it, so that solved as well.)
Add `ChainedArgsParserContext.__repr__`.
Add `SingleParserContext.__repr__`.
Add `ChainedParserContext.__repr__`.
Add `CommandContentParser.__repr__`.
Add `ContentParser.__repr__`.
Add `ContentArgumentSeparator.__repr__`.
Add `ContentArgumentSeparator.__hash__`.
Add `ContentArgumentSeparator.__eq__`.
`ContentParser` did not handled `func` correctly if `is_method` was given as `True`.
Raise `ConnectionError` over `EOFError` when reading http headers, when the other side closed the connection, before sending any data.
Raise `PayloadError` over `EOFError` when reading http headers. (Expect at the case of one above ^)
Add full name match to `Guild.get_user_like`.
Remove voice client freezing for now (and the related methods and attributes).
Silence the following exception (could still show up, but with a different call order):
```
Future exception was never retrieved
<Future FINISHED exception=gaierror(-3, 'Temporary failure in name resolution')>
Traceback (most recent call last):
  File "..../hata/backend/connector.py", line 448, in resolver_task
    event = self.dns_events[key]
KeyError(('discord.com', 443),)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "..../hata/backend/connector.py", line 461, in resolver_task
    hostinfo = await event
  File "..../hata/backend/connector.py", line 443, in resolve
    infos = await self.loop.getaddrinfo(host,port,type=module_socket.SOCK_STREAM,family=family)
  File "..../lib-python/3/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
gaierror(-3, 'Temporary failure in name resolution')
```
Add "hata/env.py".
Use env variables to determine whether hata should import only backend, not use use or cache presence.
Allow `client.events.message_edit` for uncached messages. Marked with `old_attributes` given as `None`.